devices([
  "iPhone 7",
  "iPhone 7 Plus",
  "iPhone 5s",
  "iPhone 4s",
  "iPad Air",
  "iPad Pro (12.9-inch)"
  ])

languages([
  ["en", "en_US"],
  ["de", "de_DE"],
  ["fr", "fr_FR"]
])

scheme "Depressed?UITests"

clear_previous_screenshots true
