devices([
  "iPhone 6",
  "iPhone 6 Plus",
  "iPhone 5",
  "iPhone 4s",
  "iPad Air",
  "iPad Pro"
  ])

languages([
  "en-US",
  "de-DE",
  "fr-FR"
])

scheme "Depressed?UITests"

clear_previous_screenshots
