devices([
  "iPhone 6s",
  "iPhone 6s Plus",
  "iPhone 5s",
  "iPhone 4s",
  "iPad Air 2",
  "iPad Pro"
  ])

languages([
  "en-US",
  "de-DE",
  "fr-FR"
])

scheme "Depressed?UITests"

clear_previous_screenshots
